Manga <- read.csv("L:/BUT/SD/Promo 2025/smhamdi/R/manga.csv", header = TRUE, sep = ",", dec = ".")
Anime <- read.csv("L:/BUT/SD/Promo 2025/smhamdi/R/anime.csv", header = TRUE, sep = ",", dec = ".")
class(Manga)
class(Anime)
View(Manga)
View(Anime)
dim(Manga)
dim(Anime)
mean(Manga$Score)
mean(Anime$Score)
sum(Manga$Vote)
sum(Anime$Vote)
sd(Manga$Score)
sd(Anime$Score)
#point à retravailler
quantile(Manga$Score, probs = seq(from = 0.1, to = 0.9, by = 0.1))
quantile(Anime$Score, probs = seq(from = 0.1, to = 0.9, by = 0.1))
#Les fonctions subset(), table() et prop.table()
note1 = subset(Manga, Score > 9)
nrow(note1)
note2 = subset(Manga, Vote > 200000)
nrow(note2)
note3 = subset(Manga, Vote < 200000)
nrow(note3)
note4 = subset(Manga, Score => 7 & Score <= 8)
nrow(note4)
#filtre
effectifRating = table(Anime$Rating)
print(effectifRating)
length(effectifRating)
prop.table(effectifRating)
extraction2 = subset(Anime, Rating == "R - 17+ (violence & profanity)")
nrow(extraction2)
extraction3 = subset(Anime, Rating == "R - 17+ (violence & profanity)" &
                        Score >= 8)
nrow(extraction3)
extraction4 = subset(Anime, Rating != "R - 17+ (violence & profanity)")
nrow(extraction4)
extraction5 = subset(Anime, Rating %in% c("PG - Children","G - All Ages"))
nrow(extraction5)
extraction6 = subset(Anime, !Rating %in% c("PG - Children","G - All Ages"))
nrow(extraction6)
extraction7 = subset(Anime, Score >= 9 | Vote > 400000)
nrow(extraction7)
#Les fonctions rbind() et write.table()
Anime  = Anime[ , c("Title","Score","Vote","Ranked")]
Manga = Manga[ , c("Title","Score","Vote","Ranked")]
Anime$Type = "Anime"
Manga$Type = "Manga"
Concat = rbind(Manga,Anime)
View(Concat)
write.table(x = Concat, file = "L:/BUT/SD/Promo 2025/smhamdi/R/ExportTp1.csv",
            sep = ";",row.names = FALSE)
